version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    groups:
      eslint-toolchain:
        dependency-type: "development"
        patterns:
          - "eslint"
          - "@typescript-eslint/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
